

 import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal = { family =  "JetBrainsMono Nerd Font", style="Regular" }
bold = { family =  "JetBrainsMono Nerd Font", style="Bold" }
italic = { family =  "JetBrainsMono Nerd Font", style="Italic" }
size = 11.0
[window]
startup_mode="Maximized"
opacity=0.95
