[colors.primary]
background = "#1d2021"  # Hard background
foreground = "#d4be98"

[colors.cursor]
text = "#1d2021"
cursor = "#d4be98"

[colors.normal]
black   = "#1d2021"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#32302f"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#f2e5bc"

[colors.selection]
text = "CellForeground"
background = "#3c3836"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.95  # Adjust for transparency
